=== 4ernookiy/js-ajax/src/main/resources/xml/Message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.issuetracker.training.org/Message"
	xmlns:d4="http://www.issuetracker.training.org/Message">

	<complexType name="Message">
		<sequence>
			<element name="addedBy" type="int"></element>
			<element name="addDate" type="dateTime"></element>
			<element name="text" type="string"></element>
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>

	<complexType name="Messages">
		<sequence>
			<element name="message" type="d4:Message" minOccurs="1"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<element name="messages" type="d4:Messages"></element>
</schema>

=== 4ernookiy/js-ajax/src/main/resources/xml/Message.xml
<?xml version="1.0" encoding="UTF-8"?>
<d4:messages xmlns:d4="http://www.issuetracker.training.org/Message" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.issuetracker.training.org/Message Message.xsd ">
  <message id="1">
    <addedBy>1</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Follow us @Passkeysupport for frequent tips to help aximize your group perfomance. We have an exceptional agenda in store for you at our upcoming event, but enjovable.For more information. click here...</text>
  </message>
  <message id="2">
    <addedBy>2</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Hi, Could you please send me contact list ...</text>
  </message>
  <message id="3">
    <addedBy>3</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Follow us @Passkeysupport for frequent tips to help aximize your group perfomance.</text>
  </message>
  <message id="4">
    <addedBy>1</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Hi, Could you please send me contact list ...</text>
  </message>
  <message id="5">
    <addedBy>2</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Follow us @Passkeysupport for frequent tips to help aximize your group perfomance.</text>
  </message>
  <message id="3">
    <addedBy>3</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Follow us @Passkeysupport for frequent tips to help aximize your group perfomance.</text>
  </message>
  <message id="4">
    <addedBy>2</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Hi, Could you please send me contact list ...</text>
  </message>
  <message id="5">
    <addedBy>3</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Follow us @Passkeysupport for frequent tips to help aximize your group perfomance.</text>
  </message>
  <message id="6">
    <addedBy>1</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Hi, Could you please send me contact list ...</text>
  </message>
  <message id="7">
    <addedBy>2</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Follow us @Passkeysupport for frequent tips to help aximize your group perfomance.</text>
  </message>
  <message id="8">
    <addedBy>1</addedBy>
    <addDate>2001-12-31T12:00:00</addDate>
    <text>Hi, Could you please send me contact list ...</text>
  </message>
</d4:messages>
